holiday_app/config/routes.rb
HolidayApp::Application.routes.draw do

  resources :holiday_requests

  root :to => 'holiday_requests#index'
end

holiday_app/app/models/holiday_request.rb
class HolidayRequest < OpenStruct
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def self.date_field(name)
    define_method(name) do
      parts = (1..3).to_a.map {|part| send("#{name}(#{part}i)")}
      return nil if parts.any? {|part| part.nil?}
      Date.parse(parts.join("-"))
    end
  end

  date_field :starts_on
  date_field :ends_on

  def persisted?
    false
  end
end

holiday_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

holiday_app/app/controllers/holiday_requests_controller.rb
class HolidayRequestsController < ApplicationController
  respond_to :html, :json

  def index
    @holiday_requests = Holiday::HolidayRepository.all_holiday_requests
  end

  def new
    @errors = []
    @employees = Holiday::EmployeeRepository.all_employees
    @holiday_request = HolidayRequest.new
  end

  def create
    @holiday_request = HolidayRequest.new(holiday_request_params)
    @errors = Holiday::AddHolidayRequest.new.call(@holiday_request.employee_id, @holiday_request.starts_on, @holiday_request.ends_on)

    if @errors.empty?
      redirect_to holiday_requests_path
    else
      render "new"
    end
  end

  private

  def holiday_request_params
    params.require(:holiday_request).permit(:employee_id, :starts_on, :ends_on)
  end
end

holiday_app/app/helpers/application_helper.rb
module ApplicationHelper
end

holiday_app/app/views/holiday_requests/index.html.erb
<h1>Some holiday requests</h1>
<%= link_to "New holiday request", new_holiday_request_path %>

<ul>
  <% @holiday_requests.each do |holiday_request| %>
    <li><%= holiday_request.employee.email %>: <%= holiday_request.starts_on %> to <%= holiday_request.ends_on %></li>
  <% end %>
</ul>

holiday_app/app/views/holiday_requests/new.html.erb
<% @errors.each do |error| %>
  <%= error %><br/>
<% end %>

<%= form_for @holiday_request do |f| %>
  Employee: <%= f.select :employee_id, @employees.map {|employee| [employee.email, employee.id]} %>
  <br/>
  Starts on: <%= f.date_select :starts_on %>
  <br/>
  Ends on: <%= f.date_select :ends_on %>
  <br/>
  <%= f.submit %> or <%= link_to "Cancel", holiday_requests_path %>
<% end %>

holiday_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HolidayApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>